stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    params:
    - prepare.dataset
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared/test.csv
    - data/prepared/train.csv