prepare:
  dataset: HIV.csv
  split: 0.25
  seed: 42

featurize:
  mol_representation: morganfingerprint-2-1024

train:
  max_iter: 1000
  n_est: 100
  min_split: 0.01

general:
  X: smiles
  y: HIV_active
  seed: 42